// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zenoss/cloud/data_receiver.proto

package com.zenoss.cloud;

public interface EventsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zenoss.cloud.Events)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * detailedResponse: if true, return any events that failed to be sent.
   * </pre>
   *
   * <code>bool detailedResponse = 1 [json_name = "detailedResponse"];</code>
   * @return The detailedResponse.
   */
  boolean getDetailedResponse();

  /**
   * <pre>
   * The events
   * </pre>
   *
   * <code>repeated .zenoss.cloud.Event events = 2 [json_name = "events"];</code>
   */
  java.util.List<com.zenoss.cloud.Event> 
      getEventsList();
  /**
   * <pre>
   * The events
   * </pre>
   *
   * <code>repeated .zenoss.cloud.Event events = 2 [json_name = "events"];</code>
   */
  com.zenoss.cloud.Event getEvents(int index);
  /**
   * <pre>
   * The events
   * </pre>
   *
   * <code>repeated .zenoss.cloud.Event events = 2 [json_name = "events"];</code>
   */
  int getEventsCount();
  /**
   * <pre>
   * The events
   * </pre>
   *
   * <code>repeated .zenoss.cloud.Event events = 2 [json_name = "events"];</code>
   */
  java.util.List<? extends com.zenoss.cloud.EventOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <pre>
   * The events
   * </pre>
   *
   * <code>repeated .zenoss.cloud.Event events = 2 [json_name = "events"];</code>
   */
  com.zenoss.cloud.EventOrBuilder getEventsOrBuilder(
      int index);
}
