// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: zenoss/cloud/collection_cfg.proto

package collection

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CollectionConfigService_WaitForProbeConfig_FullMethodName = "/zenoss.cloud.collection_cfg.CollectionConfigService/WaitForProbeConfig"
	CollectionConfigService_GetConfigStream_FullMethodName    = "/zenoss.cloud.collection_cfg.CollectionConfigService/GetConfigStream"
)

// CollectionConfigServiceClient is the client API for CollectionConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CollectionConfigService is the gRPC & HTTP service responsible for managing
// collection configurations.
type CollectionConfigServiceClient interface {
	WaitForProbeConfig(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WaitForProbeConfigResponse, WaitForProbeConfigRequest], error)
	GetConfigStream(ctx context.Context, in *GetConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetConfigStreamResponse], error)
}

type collectionConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectionConfigServiceClient(cc grpc.ClientConnInterface) CollectionConfigServiceClient {
	return &collectionConfigServiceClient{cc}
}

func (c *collectionConfigServiceClient) WaitForProbeConfig(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WaitForProbeConfigResponse, WaitForProbeConfigRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CollectionConfigService_ServiceDesc.Streams[0], CollectionConfigService_WaitForProbeConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WaitForProbeConfigResponse, WaitForProbeConfigRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectionConfigService_WaitForProbeConfigClient = grpc.BidiStreamingClient[WaitForProbeConfigResponse, WaitForProbeConfigRequest]

func (c *collectionConfigServiceClient) GetConfigStream(ctx context.Context, in *GetConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetConfigStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CollectionConfigService_ServiceDesc.Streams[1], CollectionConfigService_GetConfigStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetConfigStreamRequest, GetConfigStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectionConfigService_GetConfigStreamClient = grpc.ServerStreamingClient[GetConfigStreamResponse]

// CollectionConfigServiceServer is the server API for CollectionConfigService service.
// All implementations must embed UnimplementedCollectionConfigServiceServer
// for forward compatibility.
//
// CollectionConfigService is the gRPC & HTTP service responsible for managing
// collection configurations.
type CollectionConfigServiceServer interface {
	WaitForProbeConfig(grpc.BidiStreamingServer[WaitForProbeConfigResponse, WaitForProbeConfigRequest]) error
	GetConfigStream(*GetConfigStreamRequest, grpc.ServerStreamingServer[GetConfigStreamResponse]) error
	mustEmbedUnimplementedCollectionConfigServiceServer()
}

// UnimplementedCollectionConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectionConfigServiceServer struct{}

func (UnimplementedCollectionConfigServiceServer) WaitForProbeConfig(grpc.BidiStreamingServer[WaitForProbeConfigResponse, WaitForProbeConfigRequest]) error {
	return status.Errorf(codes.Unimplemented, "method WaitForProbeConfig not implemented")
}
func (UnimplementedCollectionConfigServiceServer) GetConfigStream(*GetConfigStreamRequest, grpc.ServerStreamingServer[GetConfigStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetConfigStream not implemented")
}
func (UnimplementedCollectionConfigServiceServer) mustEmbedUnimplementedCollectionConfigServiceServer() {
}
func (UnimplementedCollectionConfigServiceServer) testEmbeddedByValue() {}

// UnsafeCollectionConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectionConfigServiceServer will
// result in compilation errors.
type UnsafeCollectionConfigServiceServer interface {
	mustEmbedUnimplementedCollectionConfigServiceServer()
}

func RegisterCollectionConfigServiceServer(s grpc.ServiceRegistrar, srv CollectionConfigServiceServer) {
	// If the following call pancis, it indicates UnimplementedCollectionConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollectionConfigService_ServiceDesc, srv)
}

func _CollectionConfigService_WaitForProbeConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectionConfigServiceServer).WaitForProbeConfig(&grpc.GenericServerStream[WaitForProbeConfigResponse, WaitForProbeConfigRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectionConfigService_WaitForProbeConfigServer = grpc.BidiStreamingServer[WaitForProbeConfigResponse, WaitForProbeConfigRequest]

func _CollectionConfigService_GetConfigStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CollectionConfigServiceServer).GetConfigStream(m, &grpc.GenericServerStream[GetConfigStreamRequest, GetConfigStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectionConfigService_GetConfigStreamServer = grpc.ServerStreamingServer[GetConfigStreamResponse]

// CollectionConfigService_ServiceDesc is the grpc.ServiceDesc for CollectionConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectionConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zenoss.cloud.collection_cfg.CollectionConfigService",
	HandlerType: (*CollectionConfigServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WaitForProbeConfig",
			Handler:       _CollectionConfigService_WaitForProbeConfig_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetConfigStream",
			Handler:       _CollectionConfigService_GetConfigStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "zenoss/cloud/collection_cfg.proto",
}
