// Code generated by mockery v2.14.0. DO NOT EDIT.

package collection

import mock "github.com/stretchr/testify/mock"

// MockUnsafeCollectionConfigServiceServer is an autogenerated mock type for the UnsafeCollectionConfigServiceServer type
type MockUnsafeCollectionConfigServiceServer struct {
	mock.Mock
}

type MockUnsafeCollectionConfigServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeCollectionConfigServiceServer) EXPECT() *MockUnsafeCollectionConfigServiceServer_Expecter {
	return &MockUnsafeCollectionConfigServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedCollectionConfigServiceServer provides a mock function with given fields:
func (_m *MockUnsafeCollectionConfigServiceServer) mustEmbedUnimplementedCollectionConfigServiceServer() {
	_m.Called()
}

// MockUnsafeCollectionConfigServiceServer_mustEmbedUnimplementedCollectionConfigServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedCollectionConfigServiceServer'
type MockUnsafeCollectionConfigServiceServer_mustEmbedUnimplementedCollectionConfigServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedCollectionConfigServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeCollectionConfigServiceServer_Expecter) mustEmbedUnimplementedCollectionConfigServiceServer() *MockUnsafeCollectionConfigServiceServer_mustEmbedUnimplementedCollectionConfigServiceServer_Call {
	return &MockUnsafeCollectionConfigServiceServer_mustEmbedUnimplementedCollectionConfigServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedCollectionConfigServiceServer")}
}

func (_c *MockUnsafeCollectionConfigServiceServer_mustEmbedUnimplementedCollectionConfigServiceServer_Call) Run(run func()) *MockUnsafeCollectionConfigServiceServer_mustEmbedUnimplementedCollectionConfigServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeCollectionConfigServiceServer_mustEmbedUnimplementedCollectionConfigServiceServer_Call) Return() *MockUnsafeCollectionConfigServiceServer_mustEmbedUnimplementedCollectionConfigServiceServer_Call {
	_c.Call.Return()
	return _c
}

type mockConstructorTestingTNewMockUnsafeCollectionConfigServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUnsafeCollectionConfigServiceServer creates a new instance of MockUnsafeCollectionConfigServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUnsafeCollectionConfigServiceServer(t mockConstructorTestingTNewMockUnsafeCollectionConfigServiceServer) *MockUnsafeCollectionConfigServiceServer {
	mock := &MockUnsafeCollectionConfigServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
