// Code generated by mockery v1.0.0. DO NOT EDIT.

package collection

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockCollectionConfigServiceClient is an autogenerated mock type for the CollectionConfigServiceClient type
type MockCollectionConfigServiceClient struct {
	mock.Mock
}

// GetConfigStream provides a mock function with given fields: ctx, in, opts
func (_m *MockCollectionConfigServiceClient) GetConfigStream(ctx context.Context, in *GetConfigStreamRequest, opts ...grpc.CallOption) (CollectionConfigService_GetConfigStreamClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 CollectionConfigService_GetConfigStreamClient
	if rf, ok := ret.Get(0).(func(context.Context, *GetConfigStreamRequest, ...grpc.CallOption) CollectionConfigService_GetConfigStreamClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CollectionConfigService_GetConfigStreamClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *GetConfigStreamRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WaitForProbeConfig provides a mock function with given fields: ctx, opts
func (_m *MockCollectionConfigServiceClient) WaitForProbeConfig(ctx context.Context, opts ...grpc.CallOption) (CollectionConfigService_WaitForProbeConfigClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 CollectionConfigService_WaitForProbeConfigClient
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) CollectionConfigService_WaitForProbeConfigClient); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CollectionConfigService_WaitForProbeConfigClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
