// Code generated by mockery v2.12.2. DO NOT EDIT.

package collection

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"

	testing "testing"
)

// MockCollectionConfigService_GetConfigStreamServer is an autogenerated mock type for the CollectionConfigService_GetConfigStreamServer type
type MockCollectionConfigService_GetConfigStreamServer struct {
	mock.Mock
}

type MockCollectionConfigService_GetConfigStreamServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectionConfigService_GetConfigStreamServer) EXPECT() *MockCollectionConfigService_GetConfigStreamServer_Expecter {
	return &MockCollectionConfigService_GetConfigStreamServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with given fields:
func (_m *MockCollectionConfigService_GetConfigStreamServer) Context() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockCollectionConfigService_GetConfigStreamServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockCollectionConfigService_GetConfigStreamServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockCollectionConfigService_GetConfigStreamServer_Expecter) Context() *MockCollectionConfigService_GetConfigStreamServer_Context_Call {
	return &MockCollectionConfigService_GetConfigStreamServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockCollectionConfigService_GetConfigStreamServer_Context_Call) Run(run func()) *MockCollectionConfigService_GetConfigStreamServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCollectionConfigService_GetConfigStreamServer_Context_Call) Return(_a0 context.Context) *MockCollectionConfigService_GetConfigStreamServer_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *MockCollectionConfigService_GetConfigStreamServer) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCollectionConfigService_GetConfigStreamServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockCollectionConfigService_GetConfigStreamServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//  - m interface{}
func (_e *MockCollectionConfigService_GetConfigStreamServer_Expecter) RecvMsg(m interface{}) *MockCollectionConfigService_GetConfigStreamServer_RecvMsg_Call {
	return &MockCollectionConfigService_GetConfigStreamServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockCollectionConfigService_GetConfigStreamServer_RecvMsg_Call) Run(run func(m interface{})) *MockCollectionConfigService_GetConfigStreamServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockCollectionConfigService_GetConfigStreamServer_RecvMsg_Call) Return(_a0 error) *MockCollectionConfigService_GetConfigStreamServer_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *MockCollectionConfigService_GetConfigStreamServer) Send(_a0 *GetConfigStreamResponse) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*GetConfigStreamResponse) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCollectionConfigService_GetConfigStreamServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockCollectionConfigService_GetConfigStreamServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//  - _a0 *GetConfigStreamResponse
func (_e *MockCollectionConfigService_GetConfigStreamServer_Expecter) Send(_a0 interface{}) *MockCollectionConfigService_GetConfigStreamServer_Send_Call {
	return &MockCollectionConfigService_GetConfigStreamServer_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *MockCollectionConfigService_GetConfigStreamServer_Send_Call) Run(run func(_a0 *GetConfigStreamResponse)) *MockCollectionConfigService_GetConfigStreamServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*GetConfigStreamResponse))
	})
	return _c
}

func (_c *MockCollectionConfigService_GetConfigStreamServer_Send_Call) Return(_a0 error) *MockCollectionConfigService_GetConfigStreamServer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *MockCollectionConfigService_GetConfigStreamServer) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCollectionConfigService_GetConfigStreamServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockCollectionConfigService_GetConfigStreamServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//  - _a0 metadata.MD
func (_e *MockCollectionConfigService_GetConfigStreamServer_Expecter) SendHeader(_a0 interface{}) *MockCollectionConfigService_GetConfigStreamServer_SendHeader_Call {
	return &MockCollectionConfigService_GetConfigStreamServer_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *MockCollectionConfigService_GetConfigStreamServer_SendHeader_Call) Run(run func(_a0 metadata.MD)) *MockCollectionConfigService_GetConfigStreamServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockCollectionConfigService_GetConfigStreamServer_SendHeader_Call) Return(_a0 error) *MockCollectionConfigService_GetConfigStreamServer_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *MockCollectionConfigService_GetConfigStreamServer) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCollectionConfigService_GetConfigStreamServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockCollectionConfigService_GetConfigStreamServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//  - m interface{}
func (_e *MockCollectionConfigService_GetConfigStreamServer_Expecter) SendMsg(m interface{}) *MockCollectionConfigService_GetConfigStreamServer_SendMsg_Call {
	return &MockCollectionConfigService_GetConfigStreamServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockCollectionConfigService_GetConfigStreamServer_SendMsg_Call) Run(run func(m interface{})) *MockCollectionConfigService_GetConfigStreamServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockCollectionConfigService_GetConfigStreamServer_SendMsg_Call) Return(_a0 error) *MockCollectionConfigService_GetConfigStreamServer_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *MockCollectionConfigService_GetConfigStreamServer) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCollectionConfigService_GetConfigStreamServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockCollectionConfigService_GetConfigStreamServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//  - _a0 metadata.MD
func (_e *MockCollectionConfigService_GetConfigStreamServer_Expecter) SetHeader(_a0 interface{}) *MockCollectionConfigService_GetConfigStreamServer_SetHeader_Call {
	return &MockCollectionConfigService_GetConfigStreamServer_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *MockCollectionConfigService_GetConfigStreamServer_SetHeader_Call) Run(run func(_a0 metadata.MD)) *MockCollectionConfigService_GetConfigStreamServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockCollectionConfigService_GetConfigStreamServer_SetHeader_Call) Return(_a0 error) *MockCollectionConfigService_GetConfigStreamServer_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *MockCollectionConfigService_GetConfigStreamServer) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// MockCollectionConfigService_GetConfigStreamServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockCollectionConfigService_GetConfigStreamServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//  - _a0 metadata.MD
func (_e *MockCollectionConfigService_GetConfigStreamServer_Expecter) SetTrailer(_a0 interface{}) *MockCollectionConfigService_GetConfigStreamServer_SetTrailer_Call {
	return &MockCollectionConfigService_GetConfigStreamServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *MockCollectionConfigService_GetConfigStreamServer_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *MockCollectionConfigService_GetConfigStreamServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockCollectionConfigService_GetConfigStreamServer_SetTrailer_Call) Return() *MockCollectionConfigService_GetConfigStreamServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

// NewMockCollectionConfigService_GetConfigStreamServer creates a new instance of MockCollectionConfigService_GetConfigStreamServer. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCollectionConfigService_GetConfigStreamServer(t testing.TB) *MockCollectionConfigService_GetConfigStreamServer {
	mock := &MockCollectionConfigService_GetConfigStreamServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
