// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zenoss/cloud/data_receiver.proto

package org.zenoss.cloud.dataReceiver;

public interface CompactMetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zenoss.cloud.CompactMetric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The metric id
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * The metric id
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * The time at which the value was captured
   * </pre>
   *
   * <code>int64 timestamp = 2 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * The metric value
   * </pre>
   *
   * <code>double value = 3 [json_name = "value"];</code>
   * @return The value.
   */
  double getValue();
}
