// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zenoss/cloud/data_receiver.proto

package org.zenoss.cloud.dataReceiver;

/**
 * <pre>
 * Canonical Metric format
 * </pre>
 *
 * Protobuf type {@code zenoss.cloud.Metric}
 */
public final class Metric extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:zenoss.cloud.Metric)
    MetricOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Metric.newBuilder() to construct.
  private Metric(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Metric() {
    metric_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Metric();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Metric(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            metric_ = s;
            break;
          }
          case 16: {

            timestamp_ = input.readInt64();
            break;
          }
          case 25: {

            value_ = input.readDouble();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              dimensions_ = com.google.protobuf.MapField.newMapField(
                  DimensionsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            dimensions__ = input.readMessage(
                DimensionsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            dimensions_.getMutableMap().put(
                dimensions__.getKey(), dimensions__.getValue());
            break;
          }
          case 50: {
            com.google.protobuf.Struct.Builder subBuilder = null;
            if (metadataFields_ != null) {
              subBuilder = metadataFields_.toBuilder();
            }
            metadataFields_ = input.readMessage(com.google.protobuf.Struct.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(metadataFields_);
              metadataFields_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.zenoss.cloud.dataReceiver.DataReceiver.internal_static_zenoss_cloud_Metric_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 4:
        return internalGetDimensions();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.zenoss.cloud.dataReceiver.DataReceiver.internal_static_zenoss_cloud_Metric_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.zenoss.cloud.dataReceiver.Metric.class, org.zenoss.cloud.dataReceiver.Metric.Builder.class);
  }

  public static final int METRIC_FIELD_NUMBER = 1;
  private volatile java.lang.Object metric_;
  /**
   * <pre>
   * The metric name
   * </pre>
   *
   * <code>string metric = 1 [json_name = "metric"];</code>
   * @return The metric.
   */
  @java.lang.Override
  public java.lang.String getMetric() {
    java.lang.Object ref = metric_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      metric_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The metric name
   * </pre>
   *
   * <code>string metric = 1 [json_name = "metric"];</code>
   * @return The bytes for metric.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMetricBytes() {
    java.lang.Object ref = metric_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metric_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_;
  /**
   * <pre>
   * The time at which the value was captured
   * </pre>
   *
   * <code>int64 timestamp = 2 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int VALUE_FIELD_NUMBER = 3;
  private double value_;
  /**
   * <pre>
   * The metric value
   * </pre>
   *
   * <code>double value = 3 [json_name = "value"];</code>
   * @return The value.
   */
  @java.lang.Override
  public double getValue() {
    return value_;
  }

  public static final int DIMENSIONS_FIELD_NUMBER = 4;
  private static final class DimensionsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.zenoss.cloud.dataReceiver.DataReceiver.internal_static_zenoss_cloud_Metric_DimensionsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> dimensions_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetDimensions() {
    if (dimensions_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          DimensionsDefaultEntryHolder.defaultEntry);
    }
    return dimensions_;
  }

  public int getDimensionsCount() {
    return internalGetDimensions().getMap().size();
  }
  /**
   * <pre>
   * Dimensions associated with this datapoint.
   * </pre>
   *
   * <code>map&lt;string, string&gt; dimensions = 4 [json_name = "dimensions"];</code>
   */

  @java.lang.Override
  public boolean containsDimensions(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetDimensions().getMap().containsKey(key);
  }
  /**
   * Use {@link #getDimensionsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getDimensions() {
    return getDimensionsMap();
  }
  /**
   * <pre>
   * Dimensions associated with this datapoint.
   * </pre>
   *
   * <code>map&lt;string, string&gt; dimensions = 4 [json_name = "dimensions"];</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getDimensionsMap() {
    return internalGetDimensions().getMap();
  }
  /**
   * <pre>
   * Dimensions associated with this datapoint.
   * </pre>
   *
   * <code>map&lt;string, string&gt; dimensions = 4 [json_name = "dimensions"];</code>
   */
  @java.lang.Override

  public java.lang.String getDimensionsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetDimensions().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Dimensions associated with this datapoint.
   * </pre>
   *
   * <code>map&lt;string, string&gt; dimensions = 4 [json_name = "dimensions"];</code>
   */
  @java.lang.Override

  public java.lang.String getDimensionsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetDimensions().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int METADATAFIELDS_FIELD_NUMBER = 6;
  private com.google.protobuf.Struct metadataFields_;
  /**
   * <pre>
   * Metadata for the datapoint. Note: using Struct as it is easier than AnyArray when using json representations
   * </pre>
   *
   * <code>.google.protobuf.Struct metadataFields = 6 [json_name = "metadataFields"];</code>
   * @return Whether the metadataFields field is set.
   */
  @java.lang.Override
  public boolean hasMetadataFields() {
    return metadataFields_ != null;
  }
  /**
   * <pre>
   * Metadata for the datapoint. Note: using Struct as it is easier than AnyArray when using json representations
   * </pre>
   *
   * <code>.google.protobuf.Struct metadataFields = 6 [json_name = "metadataFields"];</code>
   * @return The metadataFields.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getMetadataFields() {
    return metadataFields_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadataFields_;
  }
  /**
   * <pre>
   * Metadata for the datapoint. Note: using Struct as it is easier than AnyArray when using json representations
   * </pre>
   *
   * <code>.google.protobuf.Struct metadataFields = 6 [json_name = "metadataFields"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getMetadataFieldsOrBuilder() {
    return getMetadataFields();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(metric_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, metric_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
      output.writeDouble(3, value_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetDimensions(),
        DimensionsDefaultEntryHolder.defaultEntry,
        4);
    if (metadataFields_ != null) {
      output.writeMessage(6, getMetadataFields());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(metric_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, metric_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestamp_);
    }
    if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, value_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetDimensions().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      dimensions__ = DimensionsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, dimensions__);
    }
    if (metadataFields_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getMetadataFields());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.zenoss.cloud.dataReceiver.Metric)) {
      return super.equals(obj);
    }
    org.zenoss.cloud.dataReceiver.Metric other = (org.zenoss.cloud.dataReceiver.Metric) obj;

    if (!getMetric()
        .equals(other.getMetric())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (java.lang.Double.doubleToLongBits(getValue())
        != java.lang.Double.doubleToLongBits(
            other.getValue())) return false;
    if (!internalGetDimensions().equals(
        other.internalGetDimensions())) return false;
    if (hasMetadataFields() != other.hasMetadataFields()) return false;
    if (hasMetadataFields()) {
      if (!getMetadataFields()
          .equals(other.getMetadataFields())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + METRIC_FIELD_NUMBER;
    hash = (53 * hash) + getMetric().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getValue()));
    if (!internalGetDimensions().getMap().isEmpty()) {
      hash = (37 * hash) + DIMENSIONS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetDimensions().hashCode();
    }
    if (hasMetadataFields()) {
      hash = (37 * hash) + METADATAFIELDS_FIELD_NUMBER;
      hash = (53 * hash) + getMetadataFields().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.zenoss.cloud.dataReceiver.Metric parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zenoss.cloud.dataReceiver.Metric parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zenoss.cloud.dataReceiver.Metric parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zenoss.cloud.dataReceiver.Metric parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zenoss.cloud.dataReceiver.Metric parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zenoss.cloud.dataReceiver.Metric parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zenoss.cloud.dataReceiver.Metric parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.zenoss.cloud.dataReceiver.Metric parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.zenoss.cloud.dataReceiver.Metric parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.zenoss.cloud.dataReceiver.Metric parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.zenoss.cloud.dataReceiver.Metric parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.zenoss.cloud.dataReceiver.Metric parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.zenoss.cloud.dataReceiver.Metric prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Canonical Metric format
   * </pre>
   *
   * Protobuf type {@code zenoss.cloud.Metric}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:zenoss.cloud.Metric)
      org.zenoss.cloud.dataReceiver.MetricOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.zenoss.cloud.dataReceiver.DataReceiver.internal_static_zenoss_cloud_Metric_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetDimensions();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableDimensions();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.zenoss.cloud.dataReceiver.DataReceiver.internal_static_zenoss_cloud_Metric_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.zenoss.cloud.dataReceiver.Metric.class, org.zenoss.cloud.dataReceiver.Metric.Builder.class);
    }

    // Construct using org.zenoss.cloud.dataReceiver.Metric.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      metric_ = "";

      timestamp_ = 0L;

      value_ = 0D;

      internalGetMutableDimensions().clear();
      if (metadataFieldsBuilder_ == null) {
        metadataFields_ = null;
      } else {
        metadataFields_ = null;
        metadataFieldsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.zenoss.cloud.dataReceiver.DataReceiver.internal_static_zenoss_cloud_Metric_descriptor;
    }

    @java.lang.Override
    public org.zenoss.cloud.dataReceiver.Metric getDefaultInstanceForType() {
      return org.zenoss.cloud.dataReceiver.Metric.getDefaultInstance();
    }

    @java.lang.Override
    public org.zenoss.cloud.dataReceiver.Metric build() {
      org.zenoss.cloud.dataReceiver.Metric result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.zenoss.cloud.dataReceiver.Metric buildPartial() {
      org.zenoss.cloud.dataReceiver.Metric result = new org.zenoss.cloud.dataReceiver.Metric(this);
      int from_bitField0_ = bitField0_;
      result.metric_ = metric_;
      result.timestamp_ = timestamp_;
      result.value_ = value_;
      result.dimensions_ = internalGetDimensions();
      result.dimensions_.makeImmutable();
      if (metadataFieldsBuilder_ == null) {
        result.metadataFields_ = metadataFields_;
      } else {
        result.metadataFields_ = metadataFieldsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.zenoss.cloud.dataReceiver.Metric) {
        return mergeFrom((org.zenoss.cloud.dataReceiver.Metric)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.zenoss.cloud.dataReceiver.Metric other) {
      if (other == org.zenoss.cloud.dataReceiver.Metric.getDefaultInstance()) return this;
      if (!other.getMetric().isEmpty()) {
        metric_ = other.metric_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getValue() != 0D) {
        setValue(other.getValue());
      }
      internalGetMutableDimensions().mergeFrom(
          other.internalGetDimensions());
      if (other.hasMetadataFields()) {
        mergeMetadataFields(other.getMetadataFields());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.zenoss.cloud.dataReceiver.Metric parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.zenoss.cloud.dataReceiver.Metric) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object metric_ = "";
    /**
     * <pre>
     * The metric name
     * </pre>
     *
     * <code>string metric = 1 [json_name = "metric"];</code>
     * @return The metric.
     */
    public java.lang.String getMetric() {
      java.lang.Object ref = metric_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metric_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The metric name
     * </pre>
     *
     * <code>string metric = 1 [json_name = "metric"];</code>
     * @return The bytes for metric.
     */
    public com.google.protobuf.ByteString
        getMetricBytes() {
      java.lang.Object ref = metric_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metric_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The metric name
     * </pre>
     *
     * <code>string metric = 1 [json_name = "metric"];</code>
     * @param value The metric to set.
     * @return This builder for chaining.
     */
    public Builder setMetric(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      metric_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The metric name
     * </pre>
     *
     * <code>string metric = 1 [json_name = "metric"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMetric() {
      
      metric_ = getDefaultInstance().getMetric();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The metric name
     * </pre>
     *
     * <code>string metric = 1 [json_name = "metric"];</code>
     * @param value The bytes for metric to set.
     * @return This builder for chaining.
     */
    public Builder setMetricBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      metric_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * The time at which the value was captured
     * </pre>
     *
     * <code>int64 timestamp = 2 [json_name = "timestamp"];</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * The time at which the value was captured
     * </pre>
     *
     * <code>int64 timestamp = 2 [json_name = "timestamp"];</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The time at which the value was captured
     * </pre>
     *
     * <code>int64 timestamp = 2 [json_name = "timestamp"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private double value_ ;
    /**
     * <pre>
     * The metric value
     * </pre>
     *
     * <code>double value = 3 [json_name = "value"];</code>
     * @return The value.
     */
    @java.lang.Override
    public double getValue() {
      return value_;
    }
    /**
     * <pre>
     * The metric value
     * </pre>
     *
     * <code>double value = 3 [json_name = "value"];</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(double value) {
      
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The metric value
     * </pre>
     *
     * <code>double value = 3 [json_name = "value"];</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      
      value_ = 0D;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> dimensions_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetDimensions() {
      if (dimensions_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DimensionsDefaultEntryHolder.defaultEntry);
      }
      return dimensions_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableDimensions() {
      onChanged();;
      if (dimensions_ == null) {
        dimensions_ = com.google.protobuf.MapField.newMapField(
            DimensionsDefaultEntryHolder.defaultEntry);
      }
      if (!dimensions_.isMutable()) {
        dimensions_ = dimensions_.copy();
      }
      return dimensions_;
    }

    public int getDimensionsCount() {
      return internalGetDimensions().getMap().size();
    }
    /**
     * <pre>
     * Dimensions associated with this datapoint.
     * </pre>
     *
     * <code>map&lt;string, string&gt; dimensions = 4 [json_name = "dimensions"];</code>
     */

    @java.lang.Override
    public boolean containsDimensions(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetDimensions().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDimensionsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getDimensions() {
      return getDimensionsMap();
    }
    /**
     * <pre>
     * Dimensions associated with this datapoint.
     * </pre>
     *
     * <code>map&lt;string, string&gt; dimensions = 4 [json_name = "dimensions"];</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getDimensionsMap() {
      return internalGetDimensions().getMap();
    }
    /**
     * <pre>
     * Dimensions associated with this datapoint.
     * </pre>
     *
     * <code>map&lt;string, string&gt; dimensions = 4 [json_name = "dimensions"];</code>
     */
    @java.lang.Override

    public java.lang.String getDimensionsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetDimensions().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Dimensions associated with this datapoint.
     * </pre>
     *
     * <code>map&lt;string, string&gt; dimensions = 4 [json_name = "dimensions"];</code>
     */
    @java.lang.Override

    public java.lang.String getDimensionsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetDimensions().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearDimensions() {
      internalGetMutableDimensions().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Dimensions associated with this datapoint.
     * </pre>
     *
     * <code>map&lt;string, string&gt; dimensions = 4 [json_name = "dimensions"];</code>
     */

    public Builder removeDimensions(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableDimensions().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableDimensions() {
      return internalGetMutableDimensions().getMutableMap();
    }
    /**
     * <pre>
     * Dimensions associated with this datapoint.
     * </pre>
     *
     * <code>map&lt;string, string&gt; dimensions = 4 [json_name = "dimensions"];</code>
     */
    public Builder putDimensions(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableDimensions().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * Dimensions associated with this datapoint.
     * </pre>
     *
     * <code>map&lt;string, string&gt; dimensions = 4 [json_name = "dimensions"];</code>
     */

    public Builder putAllDimensions(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableDimensions().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.Struct metadataFields_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> metadataFieldsBuilder_;
    /**
     * <pre>
     * Metadata for the datapoint. Note: using Struct as it is easier than AnyArray when using json representations
     * </pre>
     *
     * <code>.google.protobuf.Struct metadataFields = 6 [json_name = "metadataFields"];</code>
     * @return Whether the metadataFields field is set.
     */
    public boolean hasMetadataFields() {
      return metadataFieldsBuilder_ != null || metadataFields_ != null;
    }
    /**
     * <pre>
     * Metadata for the datapoint. Note: using Struct as it is easier than AnyArray when using json representations
     * </pre>
     *
     * <code>.google.protobuf.Struct metadataFields = 6 [json_name = "metadataFields"];</code>
     * @return The metadataFields.
     */
    public com.google.protobuf.Struct getMetadataFields() {
      if (metadataFieldsBuilder_ == null) {
        return metadataFields_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadataFields_;
      } else {
        return metadataFieldsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Metadata for the datapoint. Note: using Struct as it is easier than AnyArray when using json representations
     * </pre>
     *
     * <code>.google.protobuf.Struct metadataFields = 6 [json_name = "metadataFields"];</code>
     */
    public Builder setMetadataFields(com.google.protobuf.Struct value) {
      if (metadataFieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadataFields_ = value;
        onChanged();
      } else {
        metadataFieldsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Metadata for the datapoint. Note: using Struct as it is easier than AnyArray when using json representations
     * </pre>
     *
     * <code>.google.protobuf.Struct metadataFields = 6 [json_name = "metadataFields"];</code>
     */
    public Builder setMetadataFields(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (metadataFieldsBuilder_ == null) {
        metadataFields_ = builderForValue.build();
        onChanged();
      } else {
        metadataFieldsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Metadata for the datapoint. Note: using Struct as it is easier than AnyArray when using json representations
     * </pre>
     *
     * <code>.google.protobuf.Struct metadataFields = 6 [json_name = "metadataFields"];</code>
     */
    public Builder mergeMetadataFields(com.google.protobuf.Struct value) {
      if (metadataFieldsBuilder_ == null) {
        if (metadataFields_ != null) {
          metadataFields_ =
            com.google.protobuf.Struct.newBuilder(metadataFields_).mergeFrom(value).buildPartial();
        } else {
          metadataFields_ = value;
        }
        onChanged();
      } else {
        metadataFieldsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Metadata for the datapoint. Note: using Struct as it is easier than AnyArray when using json representations
     * </pre>
     *
     * <code>.google.protobuf.Struct metadataFields = 6 [json_name = "metadataFields"];</code>
     */
    public Builder clearMetadataFields() {
      if (metadataFieldsBuilder_ == null) {
        metadataFields_ = null;
        onChanged();
      } else {
        metadataFields_ = null;
        metadataFieldsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Metadata for the datapoint. Note: using Struct as it is easier than AnyArray when using json representations
     * </pre>
     *
     * <code>.google.protobuf.Struct metadataFields = 6 [json_name = "metadataFields"];</code>
     */
    public com.google.protobuf.Struct.Builder getMetadataFieldsBuilder() {
      
      onChanged();
      return getMetadataFieldsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Metadata for the datapoint. Note: using Struct as it is easier than AnyArray when using json representations
     * </pre>
     *
     * <code>.google.protobuf.Struct metadataFields = 6 [json_name = "metadataFields"];</code>
     */
    public com.google.protobuf.StructOrBuilder getMetadataFieldsOrBuilder() {
      if (metadataFieldsBuilder_ != null) {
        return metadataFieldsBuilder_.getMessageOrBuilder();
      } else {
        return metadataFields_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : metadataFields_;
      }
    }
    /**
     * <pre>
     * Metadata for the datapoint. Note: using Struct as it is easier than AnyArray when using json representations
     * </pre>
     *
     * <code>.google.protobuf.Struct metadataFields = 6 [json_name = "metadataFields"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getMetadataFieldsFieldBuilder() {
      if (metadataFieldsBuilder_ == null) {
        metadataFieldsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getMetadataFields(),
                getParentForChildren(),
                isClean());
        metadataFields_ = null;
      }
      return metadataFieldsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:zenoss.cloud.Metric)
  }

  // @@protoc_insertion_point(class_scope:zenoss.cloud.Metric)
  private static final org.zenoss.cloud.dataReceiver.Metric DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.zenoss.cloud.dataReceiver.Metric();
  }

  public static org.zenoss.cloud.dataReceiver.Metric getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Metric>
      PARSER = new com.google.protobuf.AbstractParser<Metric>() {
    @java.lang.Override
    public Metric parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Metric(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Metric> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Metric> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.zenoss.cloud.dataReceiver.Metric getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

