// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zenoss/cloud/data_receiver.proto

package org.zenoss.cloud.dataReceiver;

/**
 * <pre>
 * Batch of models
 * </pre>
 *
 * Protobuf type {@code zenoss.cloud.ModelBatch}
 */
public  final class ModelBatch extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:zenoss.cloud.ModelBatch)
    ModelBatchOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ModelBatch.newBuilder() to construct.
  private ModelBatch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ModelBatch() {
    models_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ModelBatch(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              globalTags_ = com.google.protobuf.MapField.newMapField(
                  GlobalTagsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            globalTags__ = input.readMessage(
                GlobalTagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            globalTags_.getMutableMap().put(
                globalTags__.getKey(), globalTags__.getValue());
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              models_ = new java.util.ArrayList<org.zenoss.cloud.dataReceiver.Model>();
              mutable_bitField0_ |= 0x00000002;
            }
            models_.add(
                input.readMessage(org.zenoss.cloud.dataReceiver.Model.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        models_ = java.util.Collections.unmodifiableList(models_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.zenoss.cloud.dataReceiver.DataReceiver.internal_static_zenoss_cloud_ModelBatch_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetGlobalTags();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.zenoss.cloud.dataReceiver.DataReceiver.internal_static_zenoss_cloud_ModelBatch_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.zenoss.cloud.dataReceiver.ModelBatch.class, org.zenoss.cloud.dataReceiver.ModelBatch.Builder.class);
  }

  public static final int GLOBAL_TAGS_FIELD_NUMBER = 1;
  private static final class GlobalTagsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.zenoss.cloud.dataReceiver.DataReceiver.internal_static_zenoss_cloud_ModelBatch_GlobalTagsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> globalTags_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetGlobalTags() {
    if (globalTags_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          GlobalTagsDefaultEntryHolder.defaultEntry);
    }
    return globalTags_;
  }

  public int getGlobalTagsCount() {
    return internalGetGlobalTags().getMap().size();
  }
  /**
   * <pre>
   * Tags that apply to all models in the batch
   * </pre>
   *
   * <code>map&lt;string, string&gt; global_tags = 1;</code>
   */

  public boolean containsGlobalTags(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetGlobalTags().getMap().containsKey(key);
  }
  /**
   * Use {@link #getGlobalTagsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getGlobalTags() {
    return getGlobalTagsMap();
  }
  /**
   * <pre>
   * Tags that apply to all models in the batch
   * </pre>
   *
   * <code>map&lt;string, string&gt; global_tags = 1;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getGlobalTagsMap() {
    return internalGetGlobalTags().getMap();
  }
  /**
   * <pre>
   * Tags that apply to all models in the batch
   * </pre>
   *
   * <code>map&lt;string, string&gt; global_tags = 1;</code>
   */

  public java.lang.String getGlobalTagsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetGlobalTags().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Tags that apply to all models in the batch
   * </pre>
   *
   * <code>map&lt;string, string&gt; global_tags = 1;</code>
   */

  public java.lang.String getGlobalTagsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetGlobalTags().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int MODELS_FIELD_NUMBER = 2;
  private java.util.List<org.zenoss.cloud.dataReceiver.Model> models_;
  /**
   * <pre>
   * The models
   * </pre>
   *
   * <code>repeated .zenoss.cloud.Model models = 2;</code>
   */
  public java.util.List<org.zenoss.cloud.dataReceiver.Model> getModelsList() {
    return models_;
  }
  /**
   * <pre>
   * The models
   * </pre>
   *
   * <code>repeated .zenoss.cloud.Model models = 2;</code>
   */
  public java.util.List<? extends org.zenoss.cloud.dataReceiver.ModelOrBuilder> 
      getModelsOrBuilderList() {
    return models_;
  }
  /**
   * <pre>
   * The models
   * </pre>
   *
   * <code>repeated .zenoss.cloud.Model models = 2;</code>
   */
  public int getModelsCount() {
    return models_.size();
  }
  /**
   * <pre>
   * The models
   * </pre>
   *
   * <code>repeated .zenoss.cloud.Model models = 2;</code>
   */
  public org.zenoss.cloud.dataReceiver.Model getModels(int index) {
    return models_.get(index);
  }
  /**
   * <pre>
   * The models
   * </pre>
   *
   * <code>repeated .zenoss.cloud.Model models = 2;</code>
   */
  public org.zenoss.cloud.dataReceiver.ModelOrBuilder getModelsOrBuilder(
      int index) {
    return models_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetGlobalTags(),
        GlobalTagsDefaultEntryHolder.defaultEntry,
        1);
    for (int i = 0; i < models_.size(); i++) {
      output.writeMessage(2, models_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetGlobalTags().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      globalTags__ = GlobalTagsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, globalTags__);
    }
    for (int i = 0; i < models_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, models_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.zenoss.cloud.dataReceiver.ModelBatch)) {
      return super.equals(obj);
    }
    org.zenoss.cloud.dataReceiver.ModelBatch other = (org.zenoss.cloud.dataReceiver.ModelBatch) obj;

    boolean result = true;
    result = result && internalGetGlobalTags().equals(
        other.internalGetGlobalTags());
    result = result && getModelsList()
        .equals(other.getModelsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetGlobalTags().getMap().isEmpty()) {
      hash = (37 * hash) + GLOBAL_TAGS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetGlobalTags().hashCode();
    }
    if (getModelsCount() > 0) {
      hash = (37 * hash) + MODELS_FIELD_NUMBER;
      hash = (53 * hash) + getModelsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.zenoss.cloud.dataReceiver.ModelBatch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zenoss.cloud.dataReceiver.ModelBatch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zenoss.cloud.dataReceiver.ModelBatch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zenoss.cloud.dataReceiver.ModelBatch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zenoss.cloud.dataReceiver.ModelBatch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zenoss.cloud.dataReceiver.ModelBatch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zenoss.cloud.dataReceiver.ModelBatch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.zenoss.cloud.dataReceiver.ModelBatch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.zenoss.cloud.dataReceiver.ModelBatch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.zenoss.cloud.dataReceiver.ModelBatch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.zenoss.cloud.dataReceiver.ModelBatch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.zenoss.cloud.dataReceiver.ModelBatch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.zenoss.cloud.dataReceiver.ModelBatch prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Batch of models
   * </pre>
   *
   * Protobuf type {@code zenoss.cloud.ModelBatch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:zenoss.cloud.ModelBatch)
      org.zenoss.cloud.dataReceiver.ModelBatchOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.zenoss.cloud.dataReceiver.DataReceiver.internal_static_zenoss_cloud_ModelBatch_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetGlobalTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableGlobalTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.zenoss.cloud.dataReceiver.DataReceiver.internal_static_zenoss_cloud_ModelBatch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.zenoss.cloud.dataReceiver.ModelBatch.class, org.zenoss.cloud.dataReceiver.ModelBatch.Builder.class);
    }

    // Construct using org.zenoss.cloud.dataReceiver.ModelBatch.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getModelsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      internalGetMutableGlobalTags().clear();
      if (modelsBuilder_ == null) {
        models_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        modelsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.zenoss.cloud.dataReceiver.DataReceiver.internal_static_zenoss_cloud_ModelBatch_descriptor;
    }

    public org.zenoss.cloud.dataReceiver.ModelBatch getDefaultInstanceForType() {
      return org.zenoss.cloud.dataReceiver.ModelBatch.getDefaultInstance();
    }

    public org.zenoss.cloud.dataReceiver.ModelBatch build() {
      org.zenoss.cloud.dataReceiver.ModelBatch result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.zenoss.cloud.dataReceiver.ModelBatch buildPartial() {
      org.zenoss.cloud.dataReceiver.ModelBatch result = new org.zenoss.cloud.dataReceiver.ModelBatch(this);
      int from_bitField0_ = bitField0_;
      result.globalTags_ = internalGetGlobalTags();
      result.globalTags_.makeImmutable();
      if (modelsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          models_ = java.util.Collections.unmodifiableList(models_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.models_ = models_;
      } else {
        result.models_ = modelsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.zenoss.cloud.dataReceiver.ModelBatch) {
        return mergeFrom((org.zenoss.cloud.dataReceiver.ModelBatch)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.zenoss.cloud.dataReceiver.ModelBatch other) {
      if (other == org.zenoss.cloud.dataReceiver.ModelBatch.getDefaultInstance()) return this;
      internalGetMutableGlobalTags().mergeFrom(
          other.internalGetGlobalTags());
      if (modelsBuilder_ == null) {
        if (!other.models_.isEmpty()) {
          if (models_.isEmpty()) {
            models_ = other.models_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureModelsIsMutable();
            models_.addAll(other.models_);
          }
          onChanged();
        }
      } else {
        if (!other.models_.isEmpty()) {
          if (modelsBuilder_.isEmpty()) {
            modelsBuilder_.dispose();
            modelsBuilder_ = null;
            models_ = other.models_;
            bitField0_ = (bitField0_ & ~0x00000002);
            modelsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getModelsFieldBuilder() : null;
          } else {
            modelsBuilder_.addAllMessages(other.models_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.zenoss.cloud.dataReceiver.ModelBatch parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.zenoss.cloud.dataReceiver.ModelBatch) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> globalTags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetGlobalTags() {
      if (globalTags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            GlobalTagsDefaultEntryHolder.defaultEntry);
      }
      return globalTags_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableGlobalTags() {
      onChanged();;
      if (globalTags_ == null) {
        globalTags_ = com.google.protobuf.MapField.newMapField(
            GlobalTagsDefaultEntryHolder.defaultEntry);
      }
      if (!globalTags_.isMutable()) {
        globalTags_ = globalTags_.copy();
      }
      return globalTags_;
    }

    public int getGlobalTagsCount() {
      return internalGetGlobalTags().getMap().size();
    }
    /**
     * <pre>
     * Tags that apply to all models in the batch
     * </pre>
     *
     * <code>map&lt;string, string&gt; global_tags = 1;</code>
     */

    public boolean containsGlobalTags(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetGlobalTags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getGlobalTagsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getGlobalTags() {
      return getGlobalTagsMap();
    }
    /**
     * <pre>
     * Tags that apply to all models in the batch
     * </pre>
     *
     * <code>map&lt;string, string&gt; global_tags = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getGlobalTagsMap() {
      return internalGetGlobalTags().getMap();
    }
    /**
     * <pre>
     * Tags that apply to all models in the batch
     * </pre>
     *
     * <code>map&lt;string, string&gt; global_tags = 1;</code>
     */

    public java.lang.String getGlobalTagsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetGlobalTags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Tags that apply to all models in the batch
     * </pre>
     *
     * <code>map&lt;string, string&gt; global_tags = 1;</code>
     */

    public java.lang.String getGlobalTagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetGlobalTags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearGlobalTags() {
      internalGetMutableGlobalTags().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Tags that apply to all models in the batch
     * </pre>
     *
     * <code>map&lt;string, string&gt; global_tags = 1;</code>
     */

    public Builder removeGlobalTags(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableGlobalTags().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableGlobalTags() {
      return internalGetMutableGlobalTags().getMutableMap();
    }
    /**
     * <pre>
     * Tags that apply to all models in the batch
     * </pre>
     *
     * <code>map&lt;string, string&gt; global_tags = 1;</code>
     */
    public Builder putGlobalTags(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableGlobalTags().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * Tags that apply to all models in the batch
     * </pre>
     *
     * <code>map&lt;string, string&gt; global_tags = 1;</code>
     */

    public Builder putAllGlobalTags(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableGlobalTags().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.util.List<org.zenoss.cloud.dataReceiver.Model> models_ =
      java.util.Collections.emptyList();
    private void ensureModelsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        models_ = new java.util.ArrayList<org.zenoss.cloud.dataReceiver.Model>(models_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.zenoss.cloud.dataReceiver.Model, org.zenoss.cloud.dataReceiver.Model.Builder, org.zenoss.cloud.dataReceiver.ModelOrBuilder> modelsBuilder_;

    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public java.util.List<org.zenoss.cloud.dataReceiver.Model> getModelsList() {
      if (modelsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(models_);
      } else {
        return modelsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public int getModelsCount() {
      if (modelsBuilder_ == null) {
        return models_.size();
      } else {
        return modelsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public org.zenoss.cloud.dataReceiver.Model getModels(int index) {
      if (modelsBuilder_ == null) {
        return models_.get(index);
      } else {
        return modelsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public Builder setModels(
        int index, org.zenoss.cloud.dataReceiver.Model value) {
      if (modelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelsIsMutable();
        models_.set(index, value);
        onChanged();
      } else {
        modelsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public Builder setModels(
        int index, org.zenoss.cloud.dataReceiver.Model.Builder builderForValue) {
      if (modelsBuilder_ == null) {
        ensureModelsIsMutable();
        models_.set(index, builderForValue.build());
        onChanged();
      } else {
        modelsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public Builder addModels(org.zenoss.cloud.dataReceiver.Model value) {
      if (modelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelsIsMutable();
        models_.add(value);
        onChanged();
      } else {
        modelsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public Builder addModels(
        int index, org.zenoss.cloud.dataReceiver.Model value) {
      if (modelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelsIsMutable();
        models_.add(index, value);
        onChanged();
      } else {
        modelsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public Builder addModels(
        org.zenoss.cloud.dataReceiver.Model.Builder builderForValue) {
      if (modelsBuilder_ == null) {
        ensureModelsIsMutable();
        models_.add(builderForValue.build());
        onChanged();
      } else {
        modelsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public Builder addModels(
        int index, org.zenoss.cloud.dataReceiver.Model.Builder builderForValue) {
      if (modelsBuilder_ == null) {
        ensureModelsIsMutable();
        models_.add(index, builderForValue.build());
        onChanged();
      } else {
        modelsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public Builder addAllModels(
        java.lang.Iterable<? extends org.zenoss.cloud.dataReceiver.Model> values) {
      if (modelsBuilder_ == null) {
        ensureModelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, models_);
        onChanged();
      } else {
        modelsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public Builder clearModels() {
      if (modelsBuilder_ == null) {
        models_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        modelsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public Builder removeModels(int index) {
      if (modelsBuilder_ == null) {
        ensureModelsIsMutable();
        models_.remove(index);
        onChanged();
      } else {
        modelsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public org.zenoss.cloud.dataReceiver.Model.Builder getModelsBuilder(
        int index) {
      return getModelsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public org.zenoss.cloud.dataReceiver.ModelOrBuilder getModelsOrBuilder(
        int index) {
      if (modelsBuilder_ == null) {
        return models_.get(index);  } else {
        return modelsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public java.util.List<? extends org.zenoss.cloud.dataReceiver.ModelOrBuilder> 
         getModelsOrBuilderList() {
      if (modelsBuilder_ != null) {
        return modelsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(models_);
      }
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public org.zenoss.cloud.dataReceiver.Model.Builder addModelsBuilder() {
      return getModelsFieldBuilder().addBuilder(
          org.zenoss.cloud.dataReceiver.Model.getDefaultInstance());
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public org.zenoss.cloud.dataReceiver.Model.Builder addModelsBuilder(
        int index) {
      return getModelsFieldBuilder().addBuilder(
          index, org.zenoss.cloud.dataReceiver.Model.getDefaultInstance());
    }
    /**
     * <pre>
     * The models
     * </pre>
     *
     * <code>repeated .zenoss.cloud.Model models = 2;</code>
     */
    public java.util.List<org.zenoss.cloud.dataReceiver.Model.Builder> 
         getModelsBuilderList() {
      return getModelsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.zenoss.cloud.dataReceiver.Model, org.zenoss.cloud.dataReceiver.Model.Builder, org.zenoss.cloud.dataReceiver.ModelOrBuilder> 
        getModelsFieldBuilder() {
      if (modelsBuilder_ == null) {
        modelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.zenoss.cloud.dataReceiver.Model, org.zenoss.cloud.dataReceiver.Model.Builder, org.zenoss.cloud.dataReceiver.ModelOrBuilder>(
                models_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        models_ = null;
      }
      return modelsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:zenoss.cloud.ModelBatch)
  }

  // @@protoc_insertion_point(class_scope:zenoss.cloud.ModelBatch)
  private static final org.zenoss.cloud.dataReceiver.ModelBatch DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.zenoss.cloud.dataReceiver.ModelBatch();
  }

  public static org.zenoss.cloud.dataReceiver.ModelBatch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ModelBatch>
      PARSER = new com.google.protobuf.AbstractParser<ModelBatch>() {
    public ModelBatch parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ModelBatch(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ModelBatch> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModelBatch> getParserForType() {
    return PARSER;
  }

  public org.zenoss.cloud.dataReceiver.ModelBatch getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

