// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zenoss/cloud/collection_cfg.proto

package com.zenoss.cloud.collection_cfg;

public interface ProbeErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zenoss.cloud.collection_cfg.ProbeError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * message is a short human-friendly text. Can be empty.
   * </pre>
   *
   * <code>string message = 3 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * message is a short human-friendly text. Can be empty.
   * </pre>
   *
   * <code>string message = 3 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * description is a parsed API error. Usually long and technical.
   * </pre>
   *
   * <code>string description = 1 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * description is a parsed API error. Usually long and technical.
   * </pre>
   *
   * <code>string description = 1 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated .zenoss.cloud.collection_cfg.FieldError field_errors = 2 [json_name = "fieldErrors"];</code>
   */
  java.util.List<com.zenoss.cloud.collection_cfg.FieldError> 
      getFieldErrorsList();
  /**
   * <code>repeated .zenoss.cloud.collection_cfg.FieldError field_errors = 2 [json_name = "fieldErrors"];</code>
   */
  com.zenoss.cloud.collection_cfg.FieldError getFieldErrors(int index);
  /**
   * <code>repeated .zenoss.cloud.collection_cfg.FieldError field_errors = 2 [json_name = "fieldErrors"];</code>
   */
  int getFieldErrorsCount();
  /**
   * <code>repeated .zenoss.cloud.collection_cfg.FieldError field_errors = 2 [json_name = "fieldErrors"];</code>
   */
  java.util.List<? extends com.zenoss.cloud.collection_cfg.FieldErrorOrBuilder> 
      getFieldErrorsOrBuilderList();
  /**
   * <code>repeated .zenoss.cloud.collection_cfg.FieldError field_errors = 2 [json_name = "fieldErrors"];</code>
   */
  com.zenoss.cloud.collection_cfg.FieldErrorOrBuilder getFieldErrorsOrBuilder(
      int index);
}
