// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zenoss/cloud/collection_cfg.proto

package com.zenoss.cloud.collection_cfg;

public interface WaitForProbeConfigRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zenoss.cloud.collection_cfg.WaitForProbeConfigRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
   * @return Whether the configuration field is set.
   */
  boolean hasConfiguration();
  /**
   * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
   * @return The configuration.
   */
  com.zenoss.cloud.collection_cfg.Config getConfiguration();
  /**
   * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
   */
  com.zenoss.cloud.collection_cfg.ConfigOrBuilder getConfigurationOrBuilder();

  /**
   * <code>int64 deadline = 2 [json_name = "deadline"];</code>
   * @return The deadline.
   */
  long getDeadline();
}
