// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zenoss/cloud/credentialsmanagement.proto

package org.zenoss.cloud.credentialsManagement;

public interface GetCredentialResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zenoss.cloud.GetCredentialResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.zenoss.cloud.Credential credential = 1 [json_name = "credential"];</code>
   * @return Whether the credential field is set.
   */
  boolean hasCredential();
  /**
   * <code>.zenoss.cloud.Credential credential = 1 [json_name = "credential"];</code>
   * @return The credential.
   */
  org.zenoss.cloud.credentialsManagement.Credential getCredential();
  /**
   * <code>.zenoss.cloud.Credential credential = 1 [json_name = "credential"];</code>
   */
  org.zenoss.cloud.credentialsManagement.CredentialOrBuilder getCredentialOrBuilder();
}
