// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zenoss/cloud/data_registry.proto

package org.zenoss.cloud.dataRegistry;

public interface GetMetricRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zenoss.cloud.GetMetricRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string instanceId = 1;</code>
   * @return The instanceId.
   */
  java.lang.String getInstanceId();
  /**
   * <code>string instanceId = 1;</code>
   * @return The bytes for instanceId.
   */
  com.google.protobuf.ByteString
      getInstanceIdBytes();
}
