// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: zenoss/cloud/credentials.proto

package credentials

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Info          *Info                  `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Secrets       map[string]string      `protobuf:"bytes,3,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_zenoss_cloud_credentials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_zenoss_cloud_credentials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_zenoss_cloud_credentials_proto_rawDescGZIP(), []int{0}
}

func (x *Credential) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Credential) GetInfo() *Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Credential) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_zenoss_cloud_credentials_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_zenoss_cloud_credentials_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_zenoss_cloud_credentials_proto_rawDescGZIP(), []int{1}
}

func (x *Info) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Info) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Info) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Info) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialRequest) Reset() {
	*x = GetCredentialRequest{}
	mi := &file_zenoss_cloud_credentials_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialRequest) ProtoMessage() {}

func (x *GetCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenoss_cloud_credentials_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialRequest) Descriptor() ([]byte, []int) {
	return file_zenoss_cloud_credentials_proto_rawDescGZIP(), []int{2}
}

func (x *GetCredentialRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialResponse) Reset() {
	*x = GetCredentialResponse{}
	mi := &file_zenoss_cloud_credentials_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialResponse) ProtoMessage() {}

func (x *GetCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zenoss_cloud_credentials_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialResponse) Descriptor() ([]byte, []int) {
	return file_zenoss_cloud_credentials_proto_rawDescGZIP(), []int{3}
}

func (x *GetCredentialResponse) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

var File_zenoss_cloud_credentials_proto protoreflect.FileDescriptor

const file_zenoss_cloud_credentials_proto_rawDesc = "" +
	"\n" +
	"\x1ezenoss/cloud/credentials.proto\x12\x18zenoss.cloud.credentials\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd9\x01\n" +
	"\n" +
	"Credential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x04info\x18\x02 \x01(\v2\x1e.zenoss.cloud.credentials.InfoR\x04info\x12K\n" +
	"\asecrets\x18\x03 \x03(\v21.zenoss.cloud.credentials.Credential.SecretsEntryR\asecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x04Info\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"&\n" +
	"\x14GetCredentialRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\x15GetCredentialResponse\x12D\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2$.zenoss.cloud.credentials.CredentialR\n" +
	"credential2\xa7\x01\n" +
	"\x14CredentialManagement\x12\x8e\x01\n" +
	"\rGetCredential\x12..zenoss.cloud.credentials.GetCredentialRequest\x1a/.zenoss.cloud.credentials.GetCredentialResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/credentials/{id}BY\n" +
	"\x1corg.zenoss.cloud.credentialsP\x01Z7github.com/zenoss/zenoss-protobufs/go/cloud/credentialsb\x06proto3"

var (
	file_zenoss_cloud_credentials_proto_rawDescOnce sync.Once
	file_zenoss_cloud_credentials_proto_rawDescData []byte
)

func file_zenoss_cloud_credentials_proto_rawDescGZIP() []byte {
	file_zenoss_cloud_credentials_proto_rawDescOnce.Do(func() {
		file_zenoss_cloud_credentials_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zenoss_cloud_credentials_proto_rawDesc), len(file_zenoss_cloud_credentials_proto_rawDesc)))
	})
	return file_zenoss_cloud_credentials_proto_rawDescData
}

var file_zenoss_cloud_credentials_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_zenoss_cloud_credentials_proto_goTypes = []any{
	(*Credential)(nil),            // 0: zenoss.cloud.credentials.Credential
	(*Info)(nil),                  // 1: zenoss.cloud.credentials.Info
	(*GetCredentialRequest)(nil),  // 2: zenoss.cloud.credentials.GetCredentialRequest
	(*GetCredentialResponse)(nil), // 3: zenoss.cloud.credentials.GetCredentialResponse
	nil,                           // 4: zenoss.cloud.credentials.Credential.SecretsEntry
}
var file_zenoss_cloud_credentials_proto_depIdxs = []int32{
	1, // 0: zenoss.cloud.credentials.Credential.info:type_name -> zenoss.cloud.credentials.Info
	4, // 1: zenoss.cloud.credentials.Credential.secrets:type_name -> zenoss.cloud.credentials.Credential.SecretsEntry
	0, // 2: zenoss.cloud.credentials.GetCredentialResponse.credential:type_name -> zenoss.cloud.credentials.Credential
	2, // 3: zenoss.cloud.credentials.CredentialManagement.GetCredential:input_type -> zenoss.cloud.credentials.GetCredentialRequest
	3, // 4: zenoss.cloud.credentials.CredentialManagement.GetCredential:output_type -> zenoss.cloud.credentials.GetCredentialResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_zenoss_cloud_credentials_proto_init() }
func file_zenoss_cloud_credentials_proto_init() {
	if File_zenoss_cloud_credentials_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zenoss_cloud_credentials_proto_rawDesc), len(file_zenoss_cloud_credentials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zenoss_cloud_credentials_proto_goTypes,
		DependencyIndexes: file_zenoss_cloud_credentials_proto_depIdxs,
		MessageInfos:      file_zenoss_cloud_credentials_proto_msgTypes,
	}.Build()
	File_zenoss_cloud_credentials_proto = out.File
	file_zenoss_cloud_credentials_proto_goTypes = nil
	file_zenoss_cloud_credentials_proto_depIdxs = nil
}
