// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: zenoss/cloud/collection_cfg.proto
// Protobuf Java Version: 4.29.3

package org.zenoss.cloud.collection;

public interface ProbeSuccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zenoss.cloud.collection_cfg.ProbeSuccess)
    com.google.protobuf.MessageOrBuilder {
}
