// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zenoss/cloud/collection_cfg.proto

// Protobuf Java Version: 4.26.1
package org.zenoss.cloud.collection;

/**
 * Protobuf type {@code zenoss.cloud.collection_cfg.WaitForProbeConfigRequest}
 */
public final class WaitForProbeConfigRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:zenoss.cloud.collection_cfg.WaitForProbeConfigRequest)
    WaitForProbeConfigRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      WaitForProbeConfigRequest.class.getName());
  }
  // Use WaitForProbeConfigRequest.newBuilder() to construct.
  private WaitForProbeConfigRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private WaitForProbeConfigRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.zenoss.cloud.collection.CollectionCfg.internal_static_zenoss_cloud_collection_cfg_WaitForProbeConfigRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.zenoss.cloud.collection.CollectionCfg.internal_static_zenoss_cloud_collection_cfg_WaitForProbeConfigRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.zenoss.cloud.collection.WaitForProbeConfigRequest.class, org.zenoss.cloud.collection.WaitForProbeConfigRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CONFIGURATION_FIELD_NUMBER = 1;
  private org.zenoss.cloud.collection.Config configuration_;
  /**
   * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
   * @return Whether the configuration field is set.
   */
  @java.lang.Override
  public boolean hasConfiguration() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
   * @return The configuration.
   */
  @java.lang.Override
  public org.zenoss.cloud.collection.Config getConfiguration() {
    return configuration_ == null ? org.zenoss.cloud.collection.Config.getDefaultInstance() : configuration_;
  }
  /**
   * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
   */
  @java.lang.Override
  public org.zenoss.cloud.collection.ConfigOrBuilder getConfigurationOrBuilder() {
    return configuration_ == null ? org.zenoss.cloud.collection.Config.getDefaultInstance() : configuration_;
  }

  public static final int DEADLINE_FIELD_NUMBER = 2;
  private long deadline_ = 0L;
  /**
   * <code>int64 deadline = 2 [json_name = "deadline"];</code>
   * @return The deadline.
   */
  @java.lang.Override
  public long getDeadline() {
    return deadline_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getConfiguration());
    }
    if (deadline_ != 0L) {
      output.writeInt64(2, deadline_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getConfiguration());
    }
    if (deadline_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, deadline_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.zenoss.cloud.collection.WaitForProbeConfigRequest)) {
      return super.equals(obj);
    }
    org.zenoss.cloud.collection.WaitForProbeConfigRequest other = (org.zenoss.cloud.collection.WaitForProbeConfigRequest) obj;

    if (hasConfiguration() != other.hasConfiguration()) return false;
    if (hasConfiguration()) {
      if (!getConfiguration()
          .equals(other.getConfiguration())) return false;
    }
    if (getDeadline()
        != other.getDeadline()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasConfiguration()) {
      hash = (37 * hash) + CONFIGURATION_FIELD_NUMBER;
      hash = (53 * hash) + getConfiguration().hashCode();
    }
    hash = (37 * hash) + DEADLINE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDeadline());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.zenoss.cloud.collection.WaitForProbeConfigRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zenoss.cloud.collection.WaitForProbeConfigRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zenoss.cloud.collection.WaitForProbeConfigRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zenoss.cloud.collection.WaitForProbeConfigRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zenoss.cloud.collection.WaitForProbeConfigRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zenoss.cloud.collection.WaitForProbeConfigRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zenoss.cloud.collection.WaitForProbeConfigRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.zenoss.cloud.collection.WaitForProbeConfigRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.zenoss.cloud.collection.WaitForProbeConfigRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.zenoss.cloud.collection.WaitForProbeConfigRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.zenoss.cloud.collection.WaitForProbeConfigRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.zenoss.cloud.collection.WaitForProbeConfigRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.zenoss.cloud.collection.WaitForProbeConfigRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code zenoss.cloud.collection_cfg.WaitForProbeConfigRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:zenoss.cloud.collection_cfg.WaitForProbeConfigRequest)
      org.zenoss.cloud.collection.WaitForProbeConfigRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.zenoss.cloud.collection.CollectionCfg.internal_static_zenoss_cloud_collection_cfg_WaitForProbeConfigRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.zenoss.cloud.collection.CollectionCfg.internal_static_zenoss_cloud_collection_cfg_WaitForProbeConfigRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.zenoss.cloud.collection.WaitForProbeConfigRequest.class, org.zenoss.cloud.collection.WaitForProbeConfigRequest.Builder.class);
    }

    // Construct using org.zenoss.cloud.collection.WaitForProbeConfigRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getConfigurationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      configuration_ = null;
      if (configurationBuilder_ != null) {
        configurationBuilder_.dispose();
        configurationBuilder_ = null;
      }
      deadline_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.zenoss.cloud.collection.CollectionCfg.internal_static_zenoss_cloud_collection_cfg_WaitForProbeConfigRequest_descriptor;
    }

    @java.lang.Override
    public org.zenoss.cloud.collection.WaitForProbeConfigRequest getDefaultInstanceForType() {
      return org.zenoss.cloud.collection.WaitForProbeConfigRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.zenoss.cloud.collection.WaitForProbeConfigRequest build() {
      org.zenoss.cloud.collection.WaitForProbeConfigRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.zenoss.cloud.collection.WaitForProbeConfigRequest buildPartial() {
      org.zenoss.cloud.collection.WaitForProbeConfigRequest result = new org.zenoss.cloud.collection.WaitForProbeConfigRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.zenoss.cloud.collection.WaitForProbeConfigRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.configuration_ = configurationBuilder_ == null
            ? configuration_
            : configurationBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.deadline_ = deadline_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.zenoss.cloud.collection.WaitForProbeConfigRequest) {
        return mergeFrom((org.zenoss.cloud.collection.WaitForProbeConfigRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.zenoss.cloud.collection.WaitForProbeConfigRequest other) {
      if (other == org.zenoss.cloud.collection.WaitForProbeConfigRequest.getDefaultInstance()) return this;
      if (other.hasConfiguration()) {
        mergeConfiguration(other.getConfiguration());
      }
      if (other.getDeadline() != 0L) {
        setDeadline(other.getDeadline());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getConfigurationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              deadline_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.zenoss.cloud.collection.Config configuration_;
    private com.google.protobuf.SingleFieldBuilder<
        org.zenoss.cloud.collection.Config, org.zenoss.cloud.collection.Config.Builder, org.zenoss.cloud.collection.ConfigOrBuilder> configurationBuilder_;
    /**
     * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
     * @return Whether the configuration field is set.
     */
    public boolean hasConfiguration() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
     * @return The configuration.
     */
    public org.zenoss.cloud.collection.Config getConfiguration() {
      if (configurationBuilder_ == null) {
        return configuration_ == null ? org.zenoss.cloud.collection.Config.getDefaultInstance() : configuration_;
      } else {
        return configurationBuilder_.getMessage();
      }
    }
    /**
     * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
     */
    public Builder setConfiguration(org.zenoss.cloud.collection.Config value) {
      if (configurationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        configuration_ = value;
      } else {
        configurationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
     */
    public Builder setConfiguration(
        org.zenoss.cloud.collection.Config.Builder builderForValue) {
      if (configurationBuilder_ == null) {
        configuration_ = builderForValue.build();
      } else {
        configurationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
     */
    public Builder mergeConfiguration(org.zenoss.cloud.collection.Config value) {
      if (configurationBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          configuration_ != null &&
          configuration_ != org.zenoss.cloud.collection.Config.getDefaultInstance()) {
          getConfigurationBuilder().mergeFrom(value);
        } else {
          configuration_ = value;
        }
      } else {
        configurationBuilder_.mergeFrom(value);
      }
      if (configuration_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
     */
    public Builder clearConfiguration() {
      bitField0_ = (bitField0_ & ~0x00000001);
      configuration_ = null;
      if (configurationBuilder_ != null) {
        configurationBuilder_.dispose();
        configurationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
     */
    public org.zenoss.cloud.collection.Config.Builder getConfigurationBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getConfigurationFieldBuilder().getBuilder();
    }
    /**
     * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
     */
    public org.zenoss.cloud.collection.ConfigOrBuilder getConfigurationOrBuilder() {
      if (configurationBuilder_ != null) {
        return configurationBuilder_.getMessageOrBuilder();
      } else {
        return configuration_ == null ?
            org.zenoss.cloud.collection.Config.getDefaultInstance() : configuration_;
      }
    }
    /**
     * <code>.zenoss.cloud.collection_cfg.Config configuration = 1 [json_name = "configuration"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.zenoss.cloud.collection.Config, org.zenoss.cloud.collection.Config.Builder, org.zenoss.cloud.collection.ConfigOrBuilder> 
        getConfigurationFieldBuilder() {
      if (configurationBuilder_ == null) {
        configurationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.zenoss.cloud.collection.Config, org.zenoss.cloud.collection.Config.Builder, org.zenoss.cloud.collection.ConfigOrBuilder>(
                getConfiguration(),
                getParentForChildren(),
                isClean());
        configuration_ = null;
      }
      return configurationBuilder_;
    }

    private long deadline_ ;
    /**
     * <code>int64 deadline = 2 [json_name = "deadline"];</code>
     * @return The deadline.
     */
    @java.lang.Override
    public long getDeadline() {
      return deadline_;
    }
    /**
     * <code>int64 deadline = 2 [json_name = "deadline"];</code>
     * @param value The deadline to set.
     * @return This builder for chaining.
     */
    public Builder setDeadline(long value) {

      deadline_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 deadline = 2 [json_name = "deadline"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeadline() {
      bitField0_ = (bitField0_ & ~0x00000002);
      deadline_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:zenoss.cloud.collection_cfg.WaitForProbeConfigRequest)
  }

  // @@protoc_insertion_point(class_scope:zenoss.cloud.collection_cfg.WaitForProbeConfigRequest)
  private static final org.zenoss.cloud.collection.WaitForProbeConfigRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.zenoss.cloud.collection.WaitForProbeConfigRequest();
  }

  public static org.zenoss.cloud.collection.WaitForProbeConfigRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WaitForProbeConfigRequest>
      PARSER = new com.google.protobuf.AbstractParser<WaitForProbeConfigRequest>() {
    @java.lang.Override
    public WaitForProbeConfigRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WaitForProbeConfigRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WaitForProbeConfigRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.zenoss.cloud.collection.WaitForProbeConfigRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

